### ISSUE TITLE
Why can't I get the auc of 97%?

### ISSUE THREAD

**Issue by justDoIt1314** [cvlab-yonsei/MNAD#1]
Use this code, Why can't I get the auc of 97%?, train 60 epochs on ped2 , get the auc of 89%

**Comment by wangyarui** [comment]
@justDoIt1314  Me too, I got the auc of 90.2.

**Comment by G-Morgen** [comment]
Me too, I got the auc of 90.2% for Ped2, 70%+ for Avenue, 57%+ for the provided pre-trained model.

**Comment by hyunjp** [comment]
Hi,
Sorry for the confusion.

This code is based on pytorch 1.1.0 version.
We find that the low performance problem occurs when the version of pytorch is more than 1.1.0.
Please set the version of pytorch to 1.1.0.

**Comment by G-Morgen** [comment]
Thanks for your great work, I can get the auc of 96.97% on ped2 using the pre-trained model after setting the version of pytorch to 1.1.0.  Could you tell me why the performance on different versions of pytorch varies so much?

**Comment by wangyarui** [comment]
我觉得也可以参考一下这个：
https://www.jianshu.com/p/1b9e18146045

**Comment by NjuHaoZhang** [comment]
> Hi,
> Sorry for the confusion.
> 
> This code is based on pytorch 1.1.0 version.
> We find that the low performance problem occurs when the version of pytorch is more than 1.1.0.
> Please set the version of pytorch to 1.1.0.

It's just so confusing. I hope the author can give some scientific explanation.

**Comment by hyunjp** [comment]
We are now looking for the reason why the upper versions of pytorch make lower performances.
We will let you know as soon as we find it.

**Comment by Smallwhite999** [comment]
> 
> 
> @justDoIt1314 Me too, I got the auc of 90.2.

Hello, have you completed the recurrence? I made a print error on the last page，
Have you encountered this problem?

Traceback (most recent call last):
  File "Train.py", line 148, in <module>
    print('Loss: Prediction {:.6f}/ Compactness {:.6f}/ Separateness {:.6f}'.format(loss_pixel.item(), compactness_loss.item(), separateness_loss.item()))
NameError: name 'loss_pixel' is not defined

**Comment by hyunjp** [comment]
Hi,
That error may come from the wrong assignment for the argparse "--method".
Please check it again ("--method pred" or "--method recon").
Thank you.

**Comment by LetterLiGo** [comment]
> Hi,
> Sorry for the confusion.
> 
> This code is based on pytorch 1.1.0 version.
> We find that the low performance problem occurs when the version of pytorch is more than 1.1.0.
> Please set the version of pytorch to 1.1.0.

Excuse me, I've tried setting the pytorch version to 1.1.0, and keeping the python version as 3.6. While I still got 90.2% on ped2 with the pre-trained model. Same as that on pytorch1.8.1

**Comment by beyondxz** [comment]
> Hi,
> Sorry for the confusion.
> 
> This code is based on pytorch 1.1.0 version.
> We find that the low performance problem occurs when the version of pytorch is more than 1.1.0.
> Please set the version of pytorch to 1.1.0.

Excuse me, I also have tried setting the pytorch version to 1.1.0, and keeping the python version as 3.6. While I still got 90.2% on ped2 with the pre-trained model. 
Could you show your other environmental dependencies? Thank you.

**Comment by beyondxz** [comment]
> Thanks for your great work, I can get the auc of 96.97% on ped2 using the pre-trained model after setting the version of pytorch to 1.1.0. Could you tell me why the performance on different versions of pytorch varies so much?

Excuse me, I also have tried setting the pytorch version to 1.1.0, and keeping the python version as 3.6. While I still got 90.2% on ped2 with the pre-trained model.
Could you show your other environmental dependencies? Thank you.

**Comment by hedachun321** [comment]
Thank you for the author's work; I think the results are quite good. This is the outcome after training for 100 epochs on ped2.
![image](https://github.com/cvlab-yonsei/MNAD/assets/62691883/2ba09ae5-147f-4460-9b16-ee895a258161)
