### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by RohDonghyeon** [cvlab-yonsei/MNAD#14]
Thanks for the perfect code.
The evaluation was able to proceed without any difficulty.
Could you please explain how to visualize the result as a picture as suggested in the paper?

**Comment by hyunjp** [comment]
Thanks for your attentions to our work.

In Fig. 4, we visualized the magnitudes of the differences between input and output images to show errors of the reconstruction (or prediction) task.
We depicted the regions of relatively large errors in red.
