### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/frame_labels_ch1.npy'

### ISSUE THREAD

**Issue by aliyevorkhan** [cvlab-yonsei/MNAD#15]
Hi, I have trained my dataset **successfully**. At the **evaluate** step I'm getting this **error**. I know I have to create labels file as _frame_labels_ch1.npy_ but **how**? I have checked your other python scripts out in your repository but I couldn't find anything about it in there. Could you guide me how to create _labels_ file as above?

**Comment by hyunjp** [comment]
The label contains the ground truth where the normal samples correspond to 0 and the abnormal ones to 1.
You can refer the uploaded labels "frame_labels_ped2.npy".

**Comment by aliyevorkhan** [comment]
Thanks so much @hyunjp . I solved.

**Comment by GS1212** [comment]
Hi! I also have this problem. How did you create the new label files (.npy)?
