### ISSUE TITLE
This code can be used in not video frame detection conditions?

### ISSUE THREAD

**Issue by l35633** [cvlab-yonsei/MNAD#16]
Hello！
First, thank you so much for this contribution.
My question:
This code is for abnormal video frame detection, I wonder if it can be used in other conditions, e.g., one small abnormal group of images different from most normal images, not video frames, but medical images etc.
Thank you !

**Comment by hyunjp** [comment]
Hi,
For implementation, we used data where the scenes are stationary.
We expect that more memory items are needed if normal samples of the medical image have lots of patterns.
