### ISSUE TITLE
dataset path error

### ISSUE THREAD

**Issue by Tiacy** [cvlab-yonsei/MNAD#17]
ValueError: num_samples should be a positive integer value, but got num_samples=0

In this code,the path  is right,while the  videos list can't be achieved by 'glob.glob(os.path.join(self.dir, '*'))' in model/utils.py.

**Comment by hyunjp** [comment]
I think the error is from different setting of the dataset path.
Please check out the dataset path and follow the instruction.

Thank you.

**Comment by duynguyentdmu** [comment]
many thanks
