### ISSUE TITLE
How to decide number of memory items "m" ? 

### ISSUE THREAD

**Issue by UsamaI000** [cvlab-yonsei/MNAD#18]
Hi, great work. There is something I would like to know. How do you decide the number of memory items? Like in your paper you used 10 memory items How do you decide that number ? Is there a rationale behind it  ?  I'll be very grateful to get an answer. Thank you

**Comment by hyunjp** [comment]
We implemented ablation study according to the number of the memory items
We found that the experiment using 10 memory items gives the best performance.
