### ISSUE TITLE
Is this model real time ?

### ISSUE THREAD

**Issue by yosagaf** [cvlab-yonsei/MNAD#2]
How to plot the abnormality score like on the video demo on the project web page ?

**Comment by njyoun** [comment]
Hi @yosagaf,  Thank you for your interest in MNAD.

Here are two answers related to your question.

1. When we define the abnormality score, we normalize each frame's score by min-max normalization(over whole video frames).
    Please see equation 16,17 in our paper.  

2. For the demo video, 
   we first computed the abnormality scores of whole test video frames and saved them for plotting.

Hope this helps.
