### ISSUE TITLE
NameError: name 'loss_pixel' is not defined

### ISSUE THREAD

**Issue by Smallwhite999** [cvlab-yonsei/MNAD#23]
I followed the steps in the readme and reported the error as follows:
/home/anaconda3/envs/MNAD/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "Train.py", line 148, in <module>
    print('Loss: Prediction {:.6f}/ Compactness {:.6f}/ Separateness {:.6f}'.format(loss_pixel.item(), compactness_loss.item(), separateness_loss.item()))
NameError: name 'loss_pixel' is not defined

How to solve it? Thank you

**Comment by hyunjp** [comment]
Hi,
That error may come from the wrong assignment for the argparse "--method".
Please check it again (You need to put it as "--method pred" or "--method recon").
Thank you.

**Comment by Wjz1203** [comment]
How did you finally solve this problem?
