### ISSUE TITLE
What's the difference between reconstruction task and prediction task?

### ISSUE THREAD

**Issue by Robert-BoMiao** [cvlab-yonsei/MNAD#3]
Hi,

I am confused about the difference between the reconstruction task and the prediction task. May I know their difference?

Thanks

**Comment by snorkeldepth** [comment]
So if I have a 30 minute video, can I just use the first 20 minutes for training and the remaining 10 minutes for prediction if I need the scores of the final 10 minutes?

**Comment by LiUzHiAn** [comment]
> Hi,
> 
> I am confused about the difference between the reconstruction task and the prediction task. May I know their difference?
> 
> Thanks

- The prediction task gets some frames(say, 4) in a video clip, then outputs the next frame, i.e. 5-th frame.
- The reconstruction task gets only one frame as input, and tries to reconstruct the frame.

**Comment by LiUzHiAn** [comment]
> So if I have a 30 minute video, can I just use the first 20 minutes for training and the remaining 10 minutes for prediction if I need the scores of the final 10 minutes?

I think you may misunderstand some concepts..., predicting 10 minutes seems too long. We feed 4 frames as input to predict the 5th frame. 

If you want to preprocess your 30-minute video as you mentioned, the key assumption you should keep in mind is that the first 20-minute frames are all normal. Hence, predicting scores for the final 10 minutes makes sense.

**Comment by Robert-BoMiao** [comment]
> > Hi,
> > I am confused about the difference between the reconstruction task and the prediction task. May I know their difference?
> > Thanks
> 
> * The prediction task gets some frames(say, 4) in a video clip, then outputs the next frame, i.e. 5-th frame.
> * The reconstruction task gets only one frame as input, and tries to reconstruct the frame.

I see. Thanks a lot.

**Comment by snorkeldepth** [comment]
> 
> 
> > So if I have a 30 minute video, can I just use the first 20 minutes for training and the remaining 10 minutes for prediction if I need the scores of the final 10 minutes?
> 
> I think you may misunderstand some concepts..., predicting 10 minutes seems too long. We feed 4 frames as input to predict the 5th frame.
> 
> If you want to preprocess your 30-minute video as you mentioned, the key assumption you should keep in mind is that the first 20-minute frames are all normal. Hence, predicting scores for the final 10 minutes makes sense.

Thanks a lot, sorry for being not as precise as I could have been. So basically all frames fed during training need to be normal/without anomalies without any exceptions, right? 

Thanks a lot already in advance, fascinating approach you & your co-authors developed! +1

**Comment by LiUzHiAn** [comment]
@snorkeldepth hi,

Yeah, the model only see frames without anomalies. You can take a look at [>>this paper<<](https://arxiv.org/abs/1712.09867) for details. Hope it helps!
