### ISSUE TITLE
Error using my own dataset

### ISSUE THREAD

**Issue by MasterMiao919** [cvlab-yonsei/MNAD#49]
Hello, when I use my own dataset for training, the following error occurs, but this error does not occur when I use CUHK Avenue. My dataset directory is as follows，can you tell me why and how to solve it? Thank you！
![image](https://user-images.githubusercontent.com/40556296/174614079-0704b788-f025-4da2-ad0b-b70f9d908453.png)
![image](https://user-images.githubusercontent.com/40556296/174614223-b6a9b922-fa21-44f3-8f04-378543a137d0.png)

**Comment by duynguyentdmu** [comment]
@MasterMiao919  i got the same error, did you solve it? please give me instructions

**Comment by MasterMiao919** [comment]
> @MasterMiao919 i got the same error, did you solve it? please give me instructions

Changed the picture name, starting with 00000.jpg
