### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

### ISSUE THREAD

**Issue by gitcheol** [cvlab-yonsei/MNAD#6]
Hi, i`m trying to experiment your model to the Shanghaitech dataset. but i got a error when evaluating the code. 
**"ValueError: Input contains NaN, infinity or a value too large for dtype('float64')."**
It would be very much appreciated if you could provide me some help.
this is my error 
<img width="865" alt="스크린샷 2020-08-25 오후 6 57 40" src="https://user-images.githubusercontent.com/37562319/91160837-e076f800-e704-11ea-8114-c48436a2468d.png">

there is a **nan** value in the **anomaly_score_tatal_list** of the Evaluate.py.
how can i solve this error?? 

All the best.

**Comment by hyunjp** [comment]
I'm not sure but I think the error comes from **anomaly_score(psnr, max_psnr, min_psnr)** which computes the division with **max_psnr-min_psnr** (max_psnr=min_psnr). 
Please make sure that your model produces the reasonable PSNR.
