### ISSUE TITLE
Unable to save recreated images and run model real time on a video

### ISSUE THREAD

**Issue by kevins99** [cvlab-yonsei/MNAD#8]
Hello! 
Thank you for your great contribution towards anomaly detection. I am currently getting started with your repo and have trained the model on the UCSD dataset. However, how do I create a demo showing the anomaly scores real time as the video plays and how do I generate the reconstructions. Is a script available for the same? Thank you!

**Comment by RohDonghyeon** [comment]
I am interested in your question.
Have you implemented the appropriate method?
