### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by linchengqiao527** [cvlab-yonsei/MNAD#9]
I test the model with your pre-trained model and memory items, but it prompts the following error：

Traceback (most recent call last):
  File "Evaluate.py", line 118, in <module>
    label_length += videos[videos_list[video_num].split('/')[-1]]['length']
IndexError: list index out of range

**Comment by dongpago** [comment]
Thanks for your work!

I have the same issue.

Could you please give me some help with this?

**Comment by hyunjp** [comment]
This error may be from the repository or different version of the data.
Please follow the instruction and check it out.
